### ISSUE TITLE
can't find orderer

### ISSUE THREAD

**Issue by jasonzhang2022** [yeasy/docker-hyperledger-fabric-orderer#2]
CMD ["orderer start"]

should be changed to CMD ["/go/bin/orderer start"]

**Comment by yeasy** [comment]
Why? The /go/bin is already in the $PATH?

$ docker run -it --rm yeasy/hyperledger-fabric-orderer bash -c 'echo $PATH'
/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by jasonzhang2022** [comment]
When I run this image for a kubernetes pod, I got this error if I don't give command
  Warning  BackOff                1m                kubelet, gke-jasoncluster-default-pool-f5cfb9d4-sxxl  Back-off restarting failed container
  Normal   Pulling                49s (x4 over 1m)  kubelet, gke-jasoncluster-default-pool-f5cfb9d4-sxxl  pulling image "yeasy/hyperledger-fabric-orderer"
  Normal   Pulled                 48s (x4 over 1m)  kubelet, gke-jasoncluster-default-pool-f5cfb9d4-sxxl  Successfully pulled image "yeasy/hyperledger-fabric-orderer"
  Normal   Created                48s (x4 over 1m)  kubelet, gke-jasoncluster-default-pool-f5cfb9d4-sxxl  Created container
  Warning  Failed                 48s (x4 over 1m)  kubelet, gke-jasoncluster-default-pool-f5cfb9d4-sxxl  Error: failed to start container "orderer": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"orderer start\": executable file not found in $PATH"
  Warning  FailedSync             48s (x5 over 1m)  kubelet, gke-jasoncluster-default-pool-f5cfb9d4-sxxl  Error syncing pod

If I have this in yaml file
command:
        #- sleep
        #- '1000000'
        - orderer
        - start
it works.

So I guess you can use the absolute path to start the orderer.

**Comment by jasonzhang2022** [comment]
the error message: "orderer start": executable file not found in $PATH"

Should CMD ["orderer start"] be changed to 
CMD ["orderer" "start"]?

**Comment by yeasy** [comment]
@jasonzhang2022 oh, u're correct.

Would you like to submit a pr for this?

**Comment by jasonzhang2022** [comment]
Would you like to submit a pr for this?

what do you mean "pr"? Patch?

**Comment by yeasy** [comment]
Yes, pr == pull request.
