### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by jasonzhang2022** [yeasy/docker-hyperledger-fabric-orderer#3]
please add LICENSE file so we know how this could be used. 
Please also add LICENSE file to other hyperledger  fabric image Dockerfile

**Comment by yeasy** [comment]
Feel free to use, and feel free to change.

Which license is even more friendly than Apache?

**Comment by jasonzhang2022** [comment]
MIT is a good choice. A LICENSE file is good. If you don't have license file, enterprise customer can't use your docker image.

I think this is a good project. I couldn't find how these binary is built in hyperledger source.

**Comment by yeasy** [comment]
Sure, and glad to find you like it.

Ok, then you can treat it as MIT license.

Still, feel free to distribute and use.
